base_dir: '/fastscratch/laadd/pipelines'
# base_dir: 'D:/IIT/DDP/data'

# basic config
fps: 30
stride_window: 100
conf_threshold: 0.3

# loading from JAX dataset
input_csv: '/projects/kumar-lab/StrainSurveyPoses/StrainSurveyMetaList_2019-04-09.tsv'
data_dir: '/projects/kumar-lab/StrainSurveyPoses'
min_video_len: 120

# preprocessing
filter_thresh: 10
bodyparts: [0, 1, 2, 3, 6, 7, 8, 9, 10, 11]

# embedding
umap_params:
  min_dist: 0.0
  n_neighbors: 90
  n_components: 35
  metric: 'cosine'

# clustering  
hdbscan_params:
  min_samples: 1
  prediction_data: True
  cluster_range: [0.4, 1.2]

# cluster pooling
cluster_thresh: 0.85
use_exemplars: True

# sampling
num_points: 600