run_id: 'dis'
base_dir: '/home/laadd/data/bsoid_data'
# base_dir: 'D:/IIT/DDP/data'

# basic config
fps: 30
stride_window: 100
conf_threshold: 0.3

# loading from JAX dataset
JAX_DATASET:
  input_csv: '/projects/kumar-lab/StrainSurveyPoses/StrainSurveyMetaList_2019-04-09.tsv'
  data_dir: '/projects/kumar-lab/StrainSurveyPoses'

# preprocessing
filter_thresh: 10
bodyparts: [0, 1, 2, 3, 6, 7, 8, 9, 10, 11]

# clustering
num_points: 3000
scale_before_umap: True

# pooling clusters
pool_thresh: 0.85
use_exemplars: True

umap_params:
  min_dist: 0.0
  n_neighbors: 90
  n_components: 35
  metric: 'cosine'
  
hdbscan_params:
  min_samples: 1
  prediction_data: True
  cluster_range: [0.4, 1.2]

trim_params:
  end_trim: 5
  clip_window: -1

clf_params:
  task_type: 'GPU'
  loss_function: 'MultiClass'
  iterations: 1500
  verbose: True
  eval_metric: 'Accuracy'